name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: 'yarn'

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn lint

  tests:
    name: "Tests - ${{ matrix.os }} - Node v${{ matrix.node-version }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu, macOS, windows]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test
